name = "Prominence II Rpg Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "498a4e9e6337e4e1241bd7da97ef00cadf9e868a6f71faab793a983f4cafd0ef"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
