name = "Prominence II [RPG]"
author = "ElocinDev"
version = "v2.8.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "067b8deece9566884eea9a3a6fb5ee9bbf14e50680f7f308aae3b4f466848b85"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
